### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Noticed there are some comments about needing to document things. Please hold off on merge until that's done.

**Comment by ghoneycutt** [comment]
@echoes-tech @floSoX 

We've updated the tests and docs and are now ready for merge.

Thanks!

**Comment by floSoX** [comment]
Hello,

Thank you for your explanations and one more time for your hard work.
You wrote :
>I'm still against inheriting the ::params class though, as the only reason to ever use inheritance is when you want to override a resource. This is to satisfy DRY, instead of repeating the resource in another class.

That exactly my need since I use this module through an ENC.
I cannot merge your PR easily it would break my integration. Moreover this code architecture is mandatory, it is a convention within my company.

To reduce the work to merge your job, can you put back the params.pp file and I will split the remaining files right after.

Thanks in advance,

**Comment by ghoneycutt** [comment]
Hi @floSoX I've run out of budget and time to continue working on this :(

I hope you find it useful and perhaps refactoring to fit your needs will be worth doing, given all the added spec testing.

Best regards,
-g

**Comment by ghoneycutt** [comment]
@petems and anyone else following. I forked this repo and released v1.0.0 which is compatible with this repo's v1.0.0, so you can port modules without worry.

https://github.com/ghoneycutt/puppet-module-monit/tree/v1.0.0

**Comment by floSoX** [comment]
Hi @ghoneycutt !

I finally took time to merge your great work to my develop branch.

Please, accept my apologies for the long delay before this merge.

I will release the v1.1.0 very soon.

Thank you very much for your hard work!

*Florent*
<http://www.echoes-tech.com/>

2016-04-22 15:30 GMT+02:00 Garrett Honeycutt <notifications@github.com>:

**Pull request closed without merging**
