### PR TITLE
Add More Mail Config Options

### PR DESCRIPTION
**Pull request by todd**
This PR proposes support for the `mailformat` and `alert` options within monitrc. Happy to make any changes necessary.

### CODE REVIEW

**Comment by floSoX** [comment]
Hi,

Thank you for your fork of my module (https://github.com/echoes-tech/puppet-monit).
I merged your work on my own branch.

Thanks a lot for your contribution.

Regards,

**Comment by todd** [comment]
Awesome, thanks! Can you cut a new version of the module and push it to the forge?

**Comment by floSoX** [comment]
It's done :-)

**Comment by todd** [comment]
:fire:

**Pull request merged**
