### PR TITLE
support for debian 9/stretch

### PR DESCRIPTION
**Pull request by to-kn**
refs #31

### CODE REVIEW

**Comment by FlorentPoinsaut** [comment]
Hello,

Thank you for this PR.
Could you please add some tests?
It would be great :-)

Thank you.
Regards,

**Comment by to-kn** [comment]
Hi,
like that? i dont think, the errors in travis have anything to do with my additions, so i leave them for now...

**Comment by to-kn** [comment]
Hi @floSoX do you need anything more?

**Comment by FlorentPoinsaut** [comment]
Hello,
I merged your work on a new repository: https://github.com/solution-libre/puppet-monit
You can find the new module here: https://forge.puppet.com/soli/monit
Regards,

**Pull request closed without merging**
